spring:
  application:
    name: dnd-11th-8-backend

  datasource:
    url: jdbc:mysql://localhost:3306/blooming
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha

auth:
  jwt:
    access:
      secret: coffeecoffeecoffeecoffeecoffeecoffeecoffeevcoffeecoffeecoffeecoffeecoffeecoffee
      expiry: 604800000
    refresh:
      secret: coffeecoffeecoffeecoffeecoffeecoffeecoffeevcoffeecoffeecoffeecoffeecoffeecoffeed
      expiry: 15552000000
  oidc:
    provider:
      kakao:
        iss: https://kauth.kakao.com
        aud: ${KAKAO_CLIENT_ID}
      apple:
        iss: https://appleid.apple.com
        aud: ${APPLE_CLIENT_ID}

cors:
  allowed-origin:
  - http://localhost:5173/
  max-age: 3600

weather:
  serviceKey: ${OPEN_API_SERVICE_KEY}

fcm:
  key: ./firebase/blooming-firebase-adminsdk.json
