spring:
  application:
    name: dnd-11th-8-backend

  datasource:
    url: jdbc:mysql://localhost:3306/blooming
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

auth:
  jwt:
    secret: coffeecoffeecoffeecoffeecoffeecoffeecoffeevcoffeecoffeecoffeecoffeecoffeecoffee
    expiration: 100000000
