version: '3.8'

services:
  mysql:
    image: mysql:8.0.29
    container_name: blooming-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blooming
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
